export const STYLE = {
  ICON_TEXT_GAP: 8,
  BASE_ANIMATION_DURATION: 300,
  HEADER_HEIGHT: 53,
  BOTTOM_HEIGHT: 70,
  NAVIGATION_HEIGHT: 62,
  TOAST_ANIMATION_DURATION: 5000,
  BOTTOM_SHEET_DURATION: 500,
  TOGGLE_ANIMATION_DURATION: 300,
  COMMENT_HEIGHT: 104,
};
