export const NOTIFICATION_MESSAGE_TYPE = {
  LOCALBOX_SUBSCRIBE: 'LOCALBOX_SUBSCRIBE',
  VILLAGE_NEWS_CONTENT_REGISTER: 'VILLAGE_NEWS_CONTENT_REGISTER',
  VILLAGE_NEWS_CONTENT_REPLY_REGISTER: 'VILLAGE_NEWS_CONTENT_REPLY_REGISTER',
  RESIDENT_NEWS_CONTENT_REPLY_REGISTER: 'RESIDENT_NEWS_CONTENT_REPLY_REGISTER',
  VILLAGE_NEWS_CONTENT_LIKE: 'VILLAGE_NEWS_CONTENT_LIKE',
  RESIDENT_NEWS_CONTENT_LIKE: 'RESIDENT_NEWS_CONTENT_LIKE',
  VILLAGE_NEWS_CONTENT_REPLY_LIKE: 'VILLAGE_NEWS_CONTENT_REPLY_LIKE',
  RESIDENT_NEWS_CONTENT_REPLY_LIKE: 'RESIDENT_NEWS_CONTENT_REPLY_LIKE',
  CONTENT_COMMON_COMPLAIN: 'CONTENT_COMMON_COMPLAIN',
  CONTENT_LOCALITY_COMPLAIN: 'CONTENT_LOCALITY_COMPLAIN',
  CONTENT_LOCALITY_COMPLAIN_BLIND_CANCEL: 'CONTENT_LOCALITY_COMPLAIN_BLIND_CANCEL',
  WILL_DEPRIVE_CONTENT_POSTING: 'WILL_DEPRIVE_CONTENT_POSTING',
  DEPRIVE_CONTENT_POSTING: 'DEPRIVE_CONTENT_POSTING',
} as const;

export const NOTIFICATION_BADGE_TYPE = {
  VILLAGE_NEWS: 'VILLAGE_NEWS',
  RESIDENT_NEWS: 'RESIDENT_NEWS',
  COMPLAIN_BLIND: 'COMPLAIN_BLIND',
} as const;

export const NOTIFICATION_ICON_TYPE = {
  MESSAGE_BUBBLE_ICON: 'MESSAGE_BUBBLE_ICON',
  STAR_ICON: 'STAR_ICON',
  BELL_ICON: 'BELL_ICON',
} as const;

export const NOTICE_MESSAGE_TYPE = {
  PRIMARY_NOTICES: 'PRIMARY_NOTICES',
  GENERAL_NOTICES: 'GENERAL_NOTICES',
} as const;

export const NOTICE_MESSAGE_TYPE_LABEL = {
  PRIMARY_NOTICES: '중요',
  GENERAL_NOTICES: '일반',
} as const;
