export const MAX_LENGTH = {
  NICKNAME: 12,
  LOGIN_ID: 12,
  MAIN_TITLE: 30,
  SIGNAGE_TITLE: 20,
  SIGNAGE_SUMMARY: 126,
  CONTENT_EDITOR: 2000,
  WORKPLACE_BUSINESS_HOURS: 50,
  SUMMARY: 50,
  COMMENT: 500,
} as const;
