export const PLACEHOLDER = {
  LOCALBOX_NICKNAME: '닉네임(1~12자 이내, 정확한 법인명 입력)*',
  NICKNAME: '닉네임 (1~12자 이내, 영문/한글/숫자 가능)*',
  ID: '아이디 (6~12자 이내, 영문/숫자 가능)*',
  PASSWORD: '비밀번호(8자이상, 문자/숫자/기호 사용가능)*',
  PASSWORD_CONFIRM: '비밀번호 재입력*',
  NAME: '이름*',
  PHONE_NUMBER: '휴대폰 번호*',
  EMAIL_NOT_REQUIRED: '이메일(선택)',
  EMAIL_REQUIRED: '이메일*',
  BUSINESS_NUMBER: '사업자 등록번호*',
  BUSINESS_NAME: '상호명*',
  BUSINESS_CONTACT_NUMBER: '전화번호*',
  BUSINESS_BASE_ADDRESS: '사업자등록증 주소*',
  DETAIL_ADDRESS: '상세주소',
  OPEN_DT: '개업일자*',
  OWNER_NAME: '대표자명*',
  CONTACT_NAME: '담당자명*',
  EMAIL_OPTIONAL: '이메일(선택)',
  SERVICE_NAME: '서비스명(선택)',
  LOCAL_NEWSPAPER_SERVICE_NAME: '신문사명*',
  NEWSPAPER_REGISTER_NUMBER: '인터넷 신문사 등록번호*',
  HOMEPAGE_URL: '홈페이지(선택): http 또는 https 시작',
  BUSINESS_LICENSE_FILE: '사업자등록증',
  EMPLOYMENT_FILE: '임명장 또는 재직증명서',
  ORGANIZATION_NAME: '아파트 단지명*',
  ORGANIZATION_CONTACT_NUMBER: '관리소 전화번호*',
  GVMT_NAME: '관공서명*',
  GVMT_CONTACT_NUMBER: '관공서 연락처*',
  GVMT_EMPLOYMENT_FILE: '공무원 재직증명서',
  WORKPLACE_BUSINESS_HOURS: '영업시간, 휴무일 정보를 입력해주세요.',
  SUMMARY: '소개글, 알림내용을 입력해주세요.',
  LOCALBOX_UNKNOWN_URL: 'SNS URL을 입력해주세요. (최대 1개)',
} as const;
